export enum CHAT_ACTIONS_TYPES {
  SET_SELECTED_CHAT = "chat/SET_SELECTED_CHAT",
  SET_CHATS = "chat/SET_CHATS",
  SET_MESSAGES = "chat/SET_MESSAGES",
  SET_FETCH_AGAIN = "chat/SET_FETCH_AGAIN",
  SET_NOTIFICATION = "chat/SET_NOTIFICATION",
}
